// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package xmpptoamqp is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Chat
*/
package xmpptoamqp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Chat struct {
	User             *string `protobuf:"bytes,1,req" json:"User,omitempty"`
	Text             *string `protobuf:"bytes,2,req" json:"Text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}

func (m *Chat) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Chat) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}
